scenarios/sno-bmh-tests/automation-vars.yml

Change to proper wait conditions for dataplane nodeset and deployment.

sno-bmh-tests: add wait condtion for dataplane

---

scenarios/sno-bmh-tests/manifests/dataplane/baremetal_hosts.yaml.j2

No suitable device was found for deployment using these hints {'name': 's== /dev/sda'}. Change to /dev/vda ...

Change sno-bmh-tests - root device hints.

---

roles/redfish_virtual_bmc/files/deployment.yaml
roles/redfish_virtual_bmc/templates/config_map.yaml.j2

Use sushy-emulator image with support for delay rebuild on eject. 
See: https://review.opendev.org/c/openstack/sushy-tools/+/945800
Also, set `SUSHY_EMULATOR_OS_VMEDIA_DELAY_EJECT = True` in config.

Update sushy-emulator image

---

scenarios/sno-bmh-tests/automation-vars.yml

Add a sleep for 30 seconds before running wait conditions, the wait command fails "error: no matching resources found".

Add a sleep for Metal platform Provisioning CR

---

scenarios/sno-bmh-tests/heat_template.yaml

Error: writing blob: adding layer with blob "...": unpacking failed (error: exit status 1;
output: open /usr/lib/python3.9/site-packages/openstackclient/tests/functional/ compute/v2/__pycache__/test_flavor.cpython-39.opt-1.pyc:
no space left on device)
fatal: [edpm-compute-2]: FAILED! =>
{"changed": false, "msg": "Failed containers: ovn_metadata_agent"}

Bump the disk size for bmh's in sno-bmh-tests

---

01-infra.yml
scenarios/3-nodes/bootstrap_vars.yml
scenarios/3-nodes/heat_template.yaml
scenarios/campus-ha/bootstrap_vars.yml
scenarios/campus-ha/heat_template.yaml
scenarios/hci/bootstrap_vars.yml
scenarios/hci/heat_template.yaml
scenarios/sno-2-bm/bootstrap_vars.yml
scenarios/sno-2-bm/heat_template.yaml
scenarios/sno-bmh-tests/bootstrap_vars.yml
scenarios/sno-bmh-tests/heat_template.yaml
scenarios/uni01alpha/bootstrap_vars.yml
scenarios/uni01alpha/heat_template.yaml

The floatingip_network was hard-coded to "public" in all the example scenario heat templates. This change adds a new variable to make that user configurable.
The bootstrap_vars.yaml files have the following new vars as example.
os_floating_network: public
os_router_external_network: public
Change those, or override on the commandline with -e <var_name> with values appropriate for the cloud being used.

Make external and fip network configurable

---

01-infra.yml
README.md
devsetup/README.md
roles/heat_stack/README.md
roles/heat_stack/tasks/main.yml
scenarios/3-nodes/bootstrap_vars.yml
scenarios/3-nodes/heat_template.yaml
scenarios/campus-ha/bootstrap_vars.yml
scenarios/campus-ha/heat_template.yaml
scenarios/hci/bootstrap_vars.yml
scenarios/hci/heat_template.yaml
scenarios/multi-ns/01-infra.yml
scenarios/multi-ns/bootstrap_vars.yml
scenarios/multi-ns/heat_template.yaml
scenarios/sno-2-bm/bootstrap_vars.yml
scenarios/sno-2-bm/heat_template.yaml
scenarios/sno-bmh-tests/bootstrap_vars.yml
scenarios/sno-bmh-tests/heat_template.yaml
scenarios/uni01alpha/bootstrap_vars.yml
scenarios/uni01alpha/heat_template.yaml

When using different clouds the default values in the heat templates need to be overriden. Flavors, images, floating ip networks etc.
Changes the "01-infra" playbook to use ansible var stack_parameters, and add a stack_parameters section in bootstrap-vars.yml for every scenario.

Move stack_parameters to bootstrap_vars

---

ipxe/README.md

Image property is not required, was added while troublshooting iPXE issue.

Revert hw_machine_type image property

---

scenarios/3-nodes/bootstrap_vars.yml
scenarios/3-nodes/heat_template.yaml
scenarios/campus-ha/bootstrap_vars.yml
scenarios/campus-ha/heat_template.yaml
scenarios/hci/bootstrap_vars.yml
scenarios/hci/heat_template.yaml
scenarios/multi-ns/bootstrap_vars.yml
scenarios/multi-ns/heat_template.yaml
scenarios/sno-2-bm/bootstrap_vars.yml
scenarios/sno-2-bm/heat_template.yaml
scenarios/sno-bmh-tests/bootstrap_vars.yml
scenarios/sno-bmh-tests/heat_template.yaml
scenarios/uni01alpha/bootstrap_vars.yml
scenarios/uni01alpha/heat_template.yaml

Operating on a cloud with bad configuration, incurrect MTU is causing a massive amount of network traffic fragmentation. Result is 7-8x degraded performance in network transfers, and a magnitude of unnececary CPU load/interupts.
Adding the value_specs, so that the MTU can be forced for the networks to use a better value.
ref: https://access.redhat.com/solutions/7059376

Add value_specs override for all networks

---

roles/redfish_virtual_bmc/templates/route.yaml.j2
scenarios/multi-ns/bootstrap_vars.yml

Some actions in sushy-emulator can take some time, up the timoutout to avoid returning 504 gateway timeout to the client.

Give sushy-emulator route a loong timeout

---

scenario-doc/source/conf.py

Building docs started failing, commenting the config fixes the issue.

Fix issue with scenario doc on `_static` not exist

---

scenarios/3-nodes/test-operator/tempest-tests.yml
scenarios/multi-ns/test-operator/tempest-tests.yml
scenarios/sno-2-bm/test-operator/tempest-tests.yml
scenarios/sno-bmh-tests/test-operator/tempest-tests.yml
scenarios/uni01alpha/test-operator/tempest-tests.yml

This has worked before, but setting the storageClass in the SPEC no longer works. If I move it to the individual workflow it works.

Fix tempest - storageClass

---

06-test-operator.yml

Need dataplane SSH public key in kernel_append_params for configuring SSH access to ironic-python-agent.

Include SSH key vars in 06-test-operator.yml

---

roles/controller/tasks/main.yml

The ansible inventory is not always needed, make it an optional and only include the task when ansible inventory is set.

controller role - make ansible inventory optional

---

02-bootstrap_controller.yml
03-install_ocp.yml
04_redfish_virtual_bmc.yml
05_deploy_rhoso.yml
06-test-operator.yml
roles/dataplane_ssh_keys/defaults/main.yml
roles/dataplane_ssh_keys/tasks/main.yml
roles/heat_stack/defaults/main.yml
roles/heat_stack/tasks/main.yml

Introduce `hotstack_work_dir` variable in roles `dataplane_ssh_keys` and `heat_stack`. Defaults to `playbook_dir`.

hotstack_work_dir var - use for storing files

---

roles/hotlogs/tasks/main.yml

Add || /bin/true to hotlog rsync command

---

roles/controller/defaults/main.yml
roles/controller/templates/clouds.yaml.j2

Inside hotstack require application credentail, simplifies the jinja template and reduces hotstack_cloud_secret var.

Only suport application credential

---

roles/controller/defaults/main.yml
roles/controller/tasks/main.yml
roles/redfish_virtual_bmc/defaults/main.yml

The hotstack controller does not need to have the clouds.yaml file in the location where openstackclient would look for it.

Move clouds yaml

---

scenarios/3-nodes/manifests/edpm/edpm.yaml
scenarios/multi-ns/manifests/dataplanes/nodesets.yaml
scenarios/sno-bmh-tests/manifests/dataplane/nodeset.yaml

Add the IP address of the hotstack controller to `edpm_sshd_allowed_ranges`.

Allow hotstack controller SSH to dataplane

---

roles/hotloop/library/hotloop_yaml_patch.py

Adds a module plug-in in the hotloop role's library that allow replacing/adding a value to YAML documents.
Example usage:
```yaml
- name: Patch Subscription channel
hotloop_yaml_patch:
file: olm.yaml
path: "spec.channel"
value: alpha
where:
- path: kind
value: Subscription
- path: metadata.name
value: openstack-operator
- path: metadata.namespace
value: openstack-operators
```

hotloop role library: hotloop_yaml_patch plug-in

---

docs/brew_builds.md
roles/hotloop/defaults/main.yml
scenarios/3-nodes/automation-vars.yml
scenarios/3-nodes/bootstrap_vars.yml
scenarios/common/scripts/brew_edpm_bootstrap_command.sh

Patch the following paths in the nodeset:
- spec.nodeTemplate.ansible.ansibleVars.edpm_podman_registries
- spec.nodeTemplate.ansible.ansibleVars.edpm_container_registry_logins
Patched with values from variables `edpm_podman_registries` and
`edpm_container_registry_logins`. By default both variables are defined
"empty". When using brew builds, the user must set these variables to
define the custom registries and login details.
Also add a brew_edpm_bootstrap_command.sh script that set podman policy
to allow insecure registries.

Brew builds - dataplane

---

docs/hotloop_lang.md
roles/hotloop/README.md
roles/hotloop/library/hotloop_stage_loader.py
roles/hotloop/tasks/execute_stage.yml
roles/hotloop/tasks/main.yml

Add `hotloop_stage_loader.py` module to hotloop role.
Module loads stages and nested stages to build a single list of stages for hotloop to execute.
This will allow for a more modular approach, where common stages cane be included from other files via ansible `lookup()` (file or template).

hotloop stage loader - nested stages

---

docs/brew_builds.md
roles/ocp_agent_installer/defaults/main.yml
roles/ocp_agent_installer/files/additional-trusted-ca-config-image.yaml
roles/ocp_agent_installer/tasks/additional_ca.yml
roles/ocp_agent_installer/tasks/config_assets.yml
roles/ocp_agent_installer/templates/additional-trusted-ca-config-map.yaml.j2

The certificates will be added to a ConfigMap resource named `hotstack-additional-trusted-ca` in the `openshift-config` namespace. And the `images.config.openshift.io` `cluster` resrouce will be configured to reference this config map in the `additionalTrustedCA` field of the resource spec.
```yaml
enable_additional_trusted_ca: true
ocp_additional_trusted_ca:
- name: reg-proxy.example.com
url: https://url.corp.redhat.com/hotstack-ca
```

Support additionalTrustedCA

---

roles/hotloop/files/common/scripts/approve_update_install_plan.sh
roles/hotloop/templates/common/stages/olm-openstack-stages.yaml.j2
roles/hotloop/templates/common/stages/openstack-olm-update.yaml.j2
scenarios/3-nodes/automation-vars.yml
scenarios/hci/automation-vars.yml
scenarios/multi-nodeset/automation-vars.yml
scenarios/multi-ns/automation-vars.yml
scenarios/sno-2-bm/automation-vars.yml
scenarios/sno-bmh-tests/automation-vars.yml
scenarios/uni01alpha/automation-vars.yml

Add support to update opentack-operator OLM.
If `openstack_operators_update` variable is boolean `true` run a script to approve the install plan if subscription is `UpgradePending`.

Support update openstack-operator OLM

---

roles/controller/defaults/main.yml
roles/controller/files/bin/hotstack-wait-for-bmh
roles/controller/tasks/main.yml
scenarios/multi-nodeset/automation-vars.yml
scenarios/multi-ns/automation-vars.yml
scenarios/sno-bmh-tests/automation-vars.yml

A script intended to run under `timeout` - wait until a BaremetalHost is one of `available`, `provsioning` or `provisioned`. Using this instead of oc wait improves re-run - with oc wait it would fail waiting for bmh to be `available` when it was already provisioned in a previous run.

Add hotstack-wait-for-bmh tool

---

docs/hotloop_lang.md
roles/hotloop/README.md
roles/hotloop/files/common/manifests/olm-openstack.yaml.j2
roles/hotloop/templates/common/stages/olm-openstack-stages.yaml.j2
roles/hotloop/templates/common/stages/openstack-olm-update.yaml.j2
update-vars.yml

Update version handling to support upstream
For upstream always use the Openstack init resource, no need to support pre-fr2.
Upstream uses: `v0.x.x`, Downstream uses: `v1.x.x`
Also drop the pre `v1.0.4` support ...

Update version handling to support upstream

---

roles/hotloop/tasks/execute_stage.yml
roles/hotloop/templates/common/stages/metal-platform-provisioning.yaml.j2
roles/hotloop/templates/common/stages/olm-deps-stages.yaml.j2
roles/hotloop/templates/common/stages/olm-openstack-stages.yaml.j2
roles/hotloop/templates/common/stages/openstack-olm-update.yaml.j2
roles/hotloop/templates/common/stages/topolvm-stages.yaml.j2
scenarios/multi-nodeset/automation-vars.yml
scenarios/multi-ns/automation-vars.yml
scenarios/sno-bmh-tests/automation-vars.yml

Only retry wait conditions if the strerr contains the matces `.*no matching resources found.*`.
This will make actual wait timeouts fail immideatly, i.e quicker fail results on actual issues.
Also tune some timeouts in the common stages.
... and fix a typo.

wait conditon retries only on no matching resource

---

scenarios/3-nodes/manifests/control-plane/control-plane.yaml

When testing upstream `v0.2.0` horizon pod end up in `CrashLoopBack`.

scenario: 3-nodes - disable horizon service

---

roles/controller/files/bin/hotstack-nova-discover-hosts
roles/controller/files/bin/hotstack-wait-for-bmh

Add script to discover and wait for compute services to match a given number of nodes.
Also fux typo and add -ex on wait-fro-bmh util

Add hotstack-nova-discover-hosts

---

roles/hotloop/templates/common/stages/openstack-olm-update.yaml.j2
scenarios/3-nodes/automation-vars.yml
scenarios/3-nodes/manifests/dataplane.yaml
scenarios/3-nodes/manifests/edpm/edpm.yaml
scenarios/3-nodes/manifests/update/update-ovn.yaml
scenarios/3-nodes/manifests/update/update-reboot.yaml
scenarios/3-nodes/manifests/update/update-services.yaml
scenarios/multi-nodeset/automation-vars.yml
scenarios/multi-nodeset/manifests/dataplane/deployment.yaml
scenarios/multi-nodeset/manifests/dataplane/nodeset.yaml
scenarios/multi-nodeset/manifests/update/update-ovn.yaml
scenarios/multi-nodeset/manifests/update/update-reboot.yaml
scenarios/multi-nodeset/manifests/update/update-services.yaml
scenarios/sno-bmh-tests/automation-vars.yml
scenarios/sno-bmh-tests/manifests/dataplane/deployment.yaml
scenarios/sno-bmh-tests/manifests/dataplane/nodeset.yaml
scenarios/sno-bmh-tests/manifests/update/update-ovn.yaml
scenarios/sno-bmh-tests/manifests/update/update-reboot.yaml
scenarios/sno-bmh-tests/manifests/update/update-services.yaml
scenarios/uni01alpha/automation-vars.yml
scenarios/uni01alpha/manifests/dataplane.yaml
scenarios/uni01alpha/manifests/edpm/edpm.yaml
scenarios/uni01alpha/manifests/networker/networker.yaml
scenarios/uni01alpha/manifests/networker/nodeset/nodeset.yaml
scenarios/uni01alpha/manifests/update/update-ovn.yaml
scenarios/uni01alpha/manifests/update/update-reboot.yaml
scenarios/uni01alpha/manifests/update/update-services.yaml

Instead of waiting for the dataplane deployment, start waits for the individual jobs that are created. The idea is to fail, fast or atleast visually indicate failure fast.
In the future we might be able to use `break_when` in the ansible loop to get faster failure.

Dataplene deployment wait on jobs.batch

---

roles/hotloop/library/hotloop_oc_apply_file.py
roles/hotloop/tasks/static_manifest.yml
roles/hotloop/tasks/template_manifest.yml
scenarios/multi-nodeset/automation-vars.yml
scenarios/multi-ns/automation-vars.yml
scenarios/sno-bmh-tests/automation-vars.yml

Add module in hotloop library `hotloop_oc_apply_file`, this module will apply the manifest file using `oc apply -f <file>` command. If successful, a backup copy is created. On re-run the module will compare the backup and the new file. If there are no changes, it will not apply the manifest again.
Update static and template manifest task files to use the new module.
Also remove the run_condition on bmh tasks, it should not be needed now that the task applying manifest no longer re-applies unchanged manifests.

hotloop - no re-apply for unchanged manifest

---

roles/ocp_agent_installer/tasks/ingress_cert.yml

Started seeing this error:
`Error from server (BadRequest): pod oauth-openshift-668d6f56cf-tcz5z does not have a host assigned`
On re-run it works ...

Add retry to Extract ingress CA cert task

---

scenarios/3-nodes/automation-vars.yml
scenarios/3-nodes/manifests/dataplane/deployment-os.yaml
scenarios/3-nodes/manifests/dataplane/deployment-services.yaml
scenarios/multi-nodeset/automation-vars.yml
scenarios/multi-nodeset/manifests/control-plane/control-plane.yaml
scenarios/multi-nodeset/manifests/dataplane/deployment-step1.yaml
scenarios/multi-nodeset/manifests/dataplane/deployment-step2.yaml

Split the dataplane deployment into two deployments. One does the bootstrap and OS part, the other OVN Openstack services.
When creating the OpenstackControlplane - initially wait only for `dns` and `OpenStackControlPlaneCAReadyCondition` conditions. Then move on and start the dataplane step 1. Once dataplane step 1 is complete, wait for OpenstackControlplane to be Ready before starting dataplane step 2.

Split dataplane deployment

---

scenarios/compact-4-bm/automation-vars.yml
scenarios/compact-4-bm/test-operator/automation-vars.yml

Add detailed documentation fields to all stages in both deployment and testing automation pipelines:
* automation-vars.yml: Document OpenStack deployment stages including dependencies, storage setup (TopoLVM, Cinder LVM), operator deployment, networking configuration, and control plane deployment with 3-replica HA setup across the compact cluster
* test-operator/automation-vars.yml: Document bare metal testing pipeline including network setup, RedFish virtual BMC configuration, OpenStack network infrastructure creation, complete Ironic node lifecycle management (enroll→manage→provide→available), and Tempest validation
The documentation provides clear explanations of each stage's purpose, how they contribute to the overall deployment/testing process, and specific details about the 4-node …

compact-4-bm: Add comprehensive documentation to automation pipelines

---

scenarios/3-nodes/heat_template.yaml
scenarios/multi-nodeset/heat_template.yaml
scenarios/multi-ns/heat_template.yaml
scenarios/sno-2-bm/heat_template.yaml
scenarios/sno-bmh-tests/heat_template.yaml

- Add haproxy load balancer configuration to sno-bmh-tests, 3-nodes, multi-nodeset, and multi-ns scenarios
- Add systemctl commands to enable and start haproxy service
- Update wildcard DNS records to point to controller instead of master node for proper load balancing

scenarios: Add haproxy config and update DNS

---

04-create-snapset.yml
README.md
ci/playbooks/pre-commit.yml
create-snapset.yml
docs/deploy_hotstack_on_psi.md
docs/hotstack_snapset.md
roles/controller/files/bin/hotstack-common-funcs.sh
roles/controller/files/bin/hotstack-snapset
roles/controller/tasks/main.yml
roles/hot_snapset/README.md
roles/hot_snapset/defaults/main.yml
roles/hot_snapset/library/hotstack_snapset.py
roles/hot_snapset/tasks/main.yml
roles/ocp_agent_installer/defaults/main.yml
roles/ocp_agent_installer/tasks/_install.yml
roles/ocp_agent_installer/tasks/config_assets.yml
roles/ocp_agent_installer/tasks/install_client.yml
roles/ocp_agent_installer/tasks/install_installer.yml
roles/ocp_agent_installer/tasks/machine_configs.yml
roles/ocp_agent_installer/tasks/main.yml
roles/ocp_agent_installer/tasks/pxe_assets.yml
scenarios/3-nodes/heat_template.yaml
scenarios/multi-nodeset/heat_template.yaml
scenarios/multi-ns/heat_template.yaml
scenarios/snapshot-sno/bootstrap_vars.yml
scenarios/snapshot-sno/heat_template.yaml
scenarios/sno-2-bm/heat_template.yaml
scenarios/sno-bmh-tests/heat_template.yaml

- Add `hotstack-snapset` utility for cluster snapshot preparation and revival.
- Support waiting for cluster stability, cordoning/uncordoning nodes, and shutdown
- Allow multiple invocations of any command for complex sequential workflows e.g. revival mode with progressive stability checks and uncordoning.
- Add snapshot preparation mode to OCP agent installer (25-hour wait + shutdown) to allow the initial 24-hour bootstrap certificate rotation to complete before creating a snapshot.
- Add hot_snapset Ansible role for snapshot management operations.

Add OCP cluster snapshot and restore capabilities

---

roles/hotloop/templates/common/stages/openstack-olm-update.yaml.j2

Whe openstack_operators_starting_csv is defined as 'null' the 'version' compare failed. Add a check that starting_csv is not none.

fix templating in openstack-olm-update.j2

---

roles/hotlogs/README.md
roles/hotlogs/defaults/main.yml
roles/hotlogs/tasks/main.yml

Adds OpenStack must-gather support to collect comprehensive diagnostic data including sushy-emulator namespace

hotlogs: add must-gather diagnostic collection

---

roles/hotlogs/tasks/main.yml

Collect all possible logs but fail at end if any collection failed.

hotlogs: track failures

---

roles/redfish_virtual_bmc/tasks/main.yml

It is ephemeral, but no need to log anyway.

redfish_virtual_bmc: no_log htpasswd task

---

roles/redfish_virtual_bmc/tasks/main.yml

When using no_log the value does not register in
register: _htpasswd and the template {{ _htpasswd.stdout }} ends up have no result.
This reverts commit 116c397c92ef0b32958f665ab672475eeb5c0fae.

Revert "redfish_virtual_bmc: no_log htpasswd task"

---

roles/hotlogs/defaults/main.yml
roles/hotlogs/library/hotlogs_must_gather.py
roles/hotlogs/tasks/main.yml

Add openstack_databases parameter to hotlogs_must_gather module, also enable collecting 'ALL' databases by default in the hotlogs role.

hotlogs: must-gather support OPENSTACK_DATABASES
