scenarios/sno-bmh-tests/manifests/dataplane/nodeset.yaml
Also remove some unnececary edpm vars.
=> Disable telemetry on dataplane

ipxe/Makefile, ipxe/README.md, ipxe/ipxe-config/general.h
Until https://github.com/ipxe/ipxe/issues/1454 is resolved we need to pin iPXE at this commit.
Also, enable serial console in iPXE.
=> Pin iPXE and enable serial console

scenarios/3-nodes/heat_template.yaml, scenarios/campus-ha/heat_template.yaml, scenarios/hci/heat_template.yaml, scenarios/multi-ns/heat_template.yaml, scenarios/sno-2-bm/heat_template.yaml, scenarios/sno-bmh-tests/heat_template.yaml, scenarios/uni01alpha/heat_template.yaml
=> Fix typo in user-data

ipxe/Makefile
The issue https://github.com/ipxe/ipxe/issues/1454 has been resolved with in (commit: https://github.com/ipxe/ipxe/commit/412ad5601).
=> Unpin iPXE - Issue resolved

devsetup/README.md, ipxe/README.md
Add more details in the readme explaining how to set up a single node packstack cloud.
=> Improve the devsetup docs

zuul.d/project.yaml
With that commit, Zuul will start trigger CI job to verify the project content.
=> Add Zuul job and nodeset

scenarios/3-nodes/automation-vars.yml, scenarios/hci/automation-vars.yml, scenarios/multi-ns/automation-vars.yml, scenarios/sno-2-bm/automation-vars.yml, scenarios/sno-bmh-tests/automation-vars.yml, scenarios/uni01alpha/automation-vars.yml
Bump:
- LEASE_DURATION: 50 (default: 30)
- RENEW_DEADLINE: 30 (default: 20)
- RETRY_PERIOD: 10 (default: 5)
=> Patch leader election tunables

docs/brew_builds.md, roles/hotloop/defaults/main.yml, roles/ocp_agent_installer/defaults/main.yml, roles/ocp_agent_installer/tasks/config_assets.yml, roles/ocp_agent_installer/templates/image-content-source-policy.yaml.j2, scenarios/3-nodes/automation-vars.yml, scenarios/hci/automation-vars.yml, scenarios/multi-ns/automation-vars.yml, scenarios/sno-2-bm/automation-vars.yml, scenarios/sno-bmh-tests/automation-vars.yml, scenarios/uni01alpha/automation-vars.yml
Add a template to set up `ImageContentSourcePolicy` based on input parameters.
Also a doc page describing how to get a token for brew registries and the variable to toggle.
=> Brew builds - to test unpublished content

scenarios/3-nodes/automation-vars.yml, scenarios/hci/automation-vars.yml, scenarios/multi-ns/automation-vars.yml, scenarios/sno-2-bm/automation-vars.yml, scenarios/sno-bmh-tests/automation-vars.yml, scenarios/uni01alpha/automation-vars.yml
Add a new wait condition after applying OLM to wait for openstack CSV to reach phase: Succeded
=> Wait for CSV openstack-operator phase: Succeeded

scenarios/3-nodes/automation-vars.yml, scenarios/hci/automation-vars.yml, scenarios/multi-ns/automation-vars.yml, scenarios/sno-2-bm/automation-vars.yml, scenarios/sno-bmh-tests/automation-vars.yml, scenarios/uni01alpha/automation-vars.yml
=> Fix typo in csv wait condition

scenarios/3-nodes/automation-vars.yml, scenarios/3-nodes/manifests/edpm/edpm.yaml, scenarios/common/scripts/upstream_edpm_bootstrap_command.sh, scenarios/hci/automation-vars.yml, scenarios/hci/manifests/edpm-pre-ceph/nodeset/nodeset.yaml, scenarios/multi-ns/automation-vars.yml, scenarios/multi-ns/manifests/dataplanes/nodesets.yaml, scenarios/sno-bmh-tests/automation-vars.yml, scenarios/sno-bmh-tests/manifests/dataplane/nodeset.yaml, scenarios/uni01alpha/automation-vars.yml, scenarios/uni01alpha/manifests/edpm/edpm.yaml, scenarios/uni01alpha/manifests/networker/nodeset/nodeset.yaml
Update all scenarios with a dataplane to use a hotloop patch for the `edpm_bootstrap_command`.
=> Use hotloop patch for edpm_bootstrap_command

roles/hotloop/library/hotloop_yaml_patch.py
Check if value is already set, and skip replacing in this case.
Also ignore the where conditions in case the doc already has the path and value defined in the patch. This allows for where conditions to match on the patch path i.e to replace only if value is `null`. NOTE: If the last key of the path is not defined, the lookup returns `None`|`null`.
```yaml
- name: Patch value in YAML if key not present or has null value
hotloop_yaml_patch:
file: /tmp/hot_patch_test.yaml
path: spec.nodeTemplate.ansible.ansibleVars.edpm_podman_registries
value: REPLACED
where:
- path: spec.nodeTemplate.ansible.ansibleVars.edpm_podman_registries
value: null
```
=> hotloop_yaml_patch - is already set

docs/hotloop_lang.md, roles/hotloop/README.md, roles/hotloop/tasks/execute_stage.yml
Adds support in a hotloop stage to only run if run conditions are met.
=> hotloop - support run_conditions for a stage

scenarios/3-nodes/bootstrap_vars.yml, scenarios/campus-ha/bootstrap_vars.yml, scenarios/hci/bootstrap_vars.yml, scenarios/multi-nodeset/bootstrap_vars.yml, scenarios/multi-ns/bootstrap_vars.yml, scenarios/sno-2-bm/bootstrap_vars.yml, scenarios/sno-bmh-tests/bootstrap_vars.yml, scenarios/uni01alpha/bootstrap_vars.yml
... the default name is too long and trunkates.
=> Remove "hotstack-" prefix

roles/hotloop/templates/common/stages/openstack-olm-update.yaml.j2
If starting CSV is pre v1.0.7 - apply the Openstack CR to initialize the new version of openstack-operators.
=> OLM Update Apply Openstack if startingCSV < v1.0.7

roles/controller/files/bin/hotstack-openstack-version-patch, roles/hotloop/templates/common/stages/openstack-olm-update.yaml.j2, scenarios/3-nodes/automation-vars.yml, scenarios/multi-nodeset/automation-vars.yml, scenarios/multi-ns/automation-vars.yml, scenarios/sno-bmh-tests/automation-vars.yml, scenarios/uni01alpha/automation-vars.yml
Add a chech that __TARGET_VERSION__ was replaced in patch file.
=> Check that __TARGET_VERSION__ replaced in patch

roles/hotloop/templates/common/stages/deps-stages.yaml.j2
Move all wait conditions for dependencies to a separate stage. Apply, everything, then wait ...
=> Separate stage for deps wait_conditions + tune

docs/minore_updates.md, roles/hotloop/templates/common/stages/openstack-olm-update.yaml.j2
Partly AI generated content ...
=> Document minor updates in hotstack

roles/hotloop/library/hotloop_oc_apply_file.py
Can't seem to `oc wait` for webhook, every now and then there is an error "no endpoints available for service".
Add a single retry if `re.search()` find a match for any of the error strings in `RETRYABLE_ERR_REGEX`.
=> hotloop_oc_apply_file - retryable errors

scenarios/compact-4-bm/manifests/control-plane/networking/nncp.yaml
... "we" forgot that this was needed in the first iteration.
Assisted-by: claude-4-sonnet
=> compact-4-bm - Add NNCP for master-1 and master-2

scenarios/compact-4-bm/test-operator/automation-vars.yml, scenarios/sno-2-bm/test-operator/automation-vars.yml
Fix number of ompuse services to expect ...
=> Ironic is just one compute service

.pre-commit-config.yaml, ci/nmstate_validate.py, ci/playbooks/pre-commit.yml
Run nmstatectl -q validate -- on all files named nncp.(yaml|yml)
Assisted-By: calude-4-sonnet
=> Add NNCP validate to pre-commit

roles/hotloop/library/hotloop_wait_condition.py, roles/hotloop/tasks/execute_stage.yml
Use a module to run wait conditions, include the retries and special case handling in the module.
Assisted-By: calude-4-sonnet
=> Add hotloop_wait_condition module

docs/hotloop_lang.md, roles/hotloop/README.md, roles/hotloop/tasks/execute_stage.yml, roles/hotloop/tasks/kustomize.yml
New stage type, apply kustomize directory.
Supports both remote and local kustomize directories.
=> Add kustomize apply stage to hotloop

roles/hotloop/library/hotloop_stage_loader.py
Allow the `kustomize` stage type and validate it.
=> hotloop_stage_loader - kustomize support

scenarios/hci/README.md, scenarios/hci/heat_template.yaml
=> Drop octavia from HCI + README updates

roles/controller/tasks/main.yml
* ansible copy expect src to be on the controller, this is problematic in case the play is run on a remote host.
=> Fix issues when running against remote host

roles/controller/tasks/main.yml, roles/hotloop/tasks/main.yml
Instead of pulling, use push ...
=> Use rsync push for workdir

zuul.d/projects.yaml
Use the github-experimental-trigger for the long running jobs.
=> Use github-experimental-trigger

scenarios/sno-2-bm/test-operator/automation-vars.yml
Add wait condtions to the stage applying the manifest for tempest via test-operator.
=> Wait for tempest - sno-2-bm

scenarios/3-nodes/test-operator/automation-vars.yml, zuul.d/jobs.yaml, zuul.d/projects.yaml
Also add AI generated documentation to stages in:
test-operator/automation-vars.yml
Assisted-By: calude-4-sonnet
=> Add 3-nodes job - experimental trigger

scenarios/uni01alpha/automation-vars.yml
The wait conditions where looking for jobs.batch resources with the incorrect name.
=> Fix jobs.batch wait conditions for network nodes
